# Generated by Django 5.2.1 on 2026-01-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_restockitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shelf_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
