# Generated by Django 5.2.1 on 2026-01-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_product_shelf_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
