# Generated by Django 5.2.1 on 2026-04-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_order_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="auto_restock_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="restock_quantity",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="product",
            name="restock_threshold",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
