# Generated by Django 5.2.1 on 2026-04-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_product_auto_restock_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "shelf_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_templates/"
                    ),
                ),
            ],
        ),
    ]
