# Generated by Django 5.2.1 on 2026-04-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_producttemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="restockitem",
            name="priority",
            field=models.IntegerField(
                choices=[(0, "FULL_EMPTY"), (1, "PARTIAL_EMPTY"), (2, "THRESHOLD")],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="restock_quantity",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="product",
            name="restock_threshold",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
